# Generated by Django 4.1.5 on 2023-01-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priceBuy',
            new_name='price_buy',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='priceSell',
            new_name='price_sell',
        ),
    ]
