# Generated by Django 4.1.5 on 2023-09-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('request', 'Request')], default='request', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('request', 'Request')], default='request', max_length=10),
        ),
    ]
