# Generated by Django 4.1.5 on 2023-09-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_type_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
